$engine: 3
$onesync: on

name: Legacy Framework (LA Underground Edition) - Native Alpha
author: Legacy
description: Installs Legacy Native Alpha (QB-free) from this GitHub repo.

tasks:
  - action: connect_database

  - action: download_github
    src: https://github.com/stevecraine1994/legacy-framework
    ref: main
    dest: ./temp/legacy

  - action: query_database
    file: ./temp/legacy/sql/legacy.sql

  - action: move_path
    src: ./temp/legacy/resources/[legacy]
    dest: ./resources/[legacy]

  - action: move_path
    src: ./temp/legacy/txadmin-recipe/server.cfg
    dest: ./server.cfg

  - action: remove_path
    path: ./temp/legacy
